name = "unmask-memory-agent"
main = "index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "MEMORY_KV"
id = "d5b23e9da4214638a62de40438bf6bc4"

[[env.production.d1_databases]]
binding = "USER_CONTEXT_D1"
database_name = "mkh-personal"
database_id = "f450193b-9536-4ada-8271-2a8cd917069e"