name = "unmask-orchestrator"
main = "intent-classifier.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "ORCHESTRATOR_KV"
id = "acec2e7241234ccfaf585c24d276ea16"

[[env.production.d1_databases]]
binding = "USER_CONTEXT_D1"
database_name = "mkh-personal"
database_id = "f450193b-9536-4ada-8271-2a8cd917069e"